### ISSUE TITLE
youtube video downloading: panic: unexpected status code: 400

### ISSUE THREAD

**Issue by xihajun** [appleboy/go-whisper#43]
https://github.com/appleboy/go-whisper/blob/53b9fb101f51bcf1d67ddd5a2a393f6de038606c/youtube/youtube.go#L81-L87

```
panic: unexpected status code: 400

goroutine 1 [running]:
github.com/appleboy/go-whisper/youtube.(*Engine).download(0xc0002715b8, {0xd4bbe0, 0x14a2b80}, {0xd45980?, 0xc00014db80})
	/app/youtube/youtube.go:86 +0x418
github.com/appleboy/go-whisper/youtube.(*Engine).Download(0xc0002715b8, {0xd4bbe0, 0x14a2b80})
	/app/youtube/youtube.go:62 +0x285
main.run(0xc0001ce160?)
	/app/main.go:242 +0xa70
github.com/urfave/cli/v2.(*Command).Run(0xc0001ce160, 0xc00007d7c0, {0xc0000360c0, 0x1, 0x1})
	/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:279 +0x9dd
github.com/urfave/cli/v2.(*App).RunContext(0xc000124200, {0xd4bbe0?, 0x14a2b80}, {0xc0000360c0, 0x1, 0x1})
	/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:337 +0x5db
github.com/urfave/cli/v2.(*App).Run(...)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:311
main.main()
	/app/main.go:185 +0x18d0
```

**Comment by bertrandgorge** [comment]
Still there!
